title:            SavvyClutch Engineering Club
description:      Work notes.
# put your disqus here
disqus_shortname: 
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://www.savvyclutch.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
#  - title: 'Home'
#    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
#  - title: 'Favorites'
#    url: '#'
#    submenu:
#      - title: 'Code Highlighter'
#        url: '/intro/code-highlighting-post/'
#      - title: 'Sample Post'
#        url: '/intro/sample-post/'

# Owner/author information
#owner:
#  name:           Your name
#  site:           http://aronbordin.com
#  avatar:         images/avatar.jpg
#  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
#  email:          you@email.com
  # Twitter nick for use in Twitter cards and follow button.
#  twitter: aron_bordin # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
#  github: aron-bordin

authors:
  bogdan:
    name: Bogdan Frankovskyi
    display_name: Bogdan
    gravatar: 096968a285ac70270237bc78e0bb57cb
    email: bogdan@savvyclutch.com
    site: http://savvyclutch.com
    bio: "I'm Software Engeneer."
#    twitter: company
#    github: hhattori
  sergii:
    name: Sergii Naumenko
    display_name: Sergii
#    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    bio: "I'm Software Engeneer at [Intelliarts](http://intelliarts.com/)."
    email: sergii@savvyclutch.com
  andrii:
    name: Andrii Kozlovskyi
    display_name: Andrii
  #    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    bio: "I'm Software Engeneer at [Intelliarts](http://intelliarts.com/)."
    email: andrii@savvyclutch.com
  vova:
    name: Volodymyr Kelembet
    display_name: Volodymyr
  #    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    bio: "I'm Software Engeneer at [Intelliarts](http://intelliarts.com/)."
    email: vova@savvyclutch.com

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
#social:
#  - title: "github"
#    url: "https://github.com/aron-bordin"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80919305-1
google_verify: 4Prb4mX_Z9i72d8nLReB60cMwtmV_CN1llKlIMPweco
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Uzhgorod
locale:      en_US
future:      true
markdown:    kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
#  enable_coderay: true
#
#  coderay:
#    coderay_line_numbers: nil
#    coderay_line_numbers_start: 1
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
